package br.com.bb.dsc.enums;

public enum MetricasEnum {

    GMC_INFORMATICA_TEMPO_EXECUCAO,
    GMC_INFORMATICA_ELEMENTOS_TOTAL,
    GMC_INFORMATICA_ELEMENTOS_ATUALIZADOS,
    GMC_INFORMATICA_ELEMENTOS_ERROS,
    GMC_INFORMATICA_HISTORICO_TOTAL,
    GMC_INFORMATICA_HISTORICO_ATUALIZADOS,
    GMC_INFORMATICA_HISTORICO_ERROS;

}
